llm:
  provider: "openai"
  models:
    default:
      name: "gpt-4"
      api_key: "${OPENAI_API_KEY}"
      max_tokens: 2000
      temperature: 0.7
    fine_tuned:
      name: "ft:gpt-3.5-turbo-0613:acme-corp::7qCrVKmR"
      api_key: "${OPENAI_API_KEY}"
      max_tokens: 1000
      temperature: 0.5
  use_fine_tuned: false
  fallback_strategy: "default_model"
  rate_limit:
    requests_per_minute: 60
  retry:
    max_attempts: 3
    initial_delay: 1
    backoff_factor: 2

alternative_providers:
  anthropic:
    api_key: "${ANTHROPIC_API_KEY}"
    model: "claude-2"
    max_tokens: 2000
    temperature: 0.7
  huggingface:
    api_key: "${HF_API_KEY}"
    model: "bigscience/bloom"
    max_tokens: 1000
    temperature: 0.8

caching:
  enabled: true
  type: "redis"
  host: "localhost"
  port: 6379
  ttl: 3600

prompt_templates:
  incident_understanding: |
    Analyze the following incident and provide a detailed understanding:

    Incident ID: {incident_id}
    Timestamp: {timestamp}
    Description: {description}

    Please provide:
    1. A summary of the incident
    2. Potential impact and severity (on a scale of 1-10)
    3. Key elements to investigate
    4. Relevant log sources to check
    5. Any initial hypotheses about the nature of the incident (e.g., potential fraud patterns, suspicious activities)
    6. Recommended immediate actions

  anomaly_detection: |
    Analyze the following logs for anomalies related to the incident:

    Incident Understanding:
    {incident_understanding}

    Logs:
    {logs}

    Identify any anomalies, suspicious patterns, or indicators of fraud. For each anomaly, provide:
    1. A description of the anomaly
    2. The relevant log entries or data points
    3. The potential implications or risks associated with this anomaly
    4. A confidence score (0-1) indicating how certain you are that this is a genuine anomaly
    5. Recommended actions to investigate or mitigate this anomaly

  report_generation: |
    Generate a detailed fraud investigation report based on the following information:

    Incident:
    {incident}

    Understanding:
    {understanding}

    Anomalies:
    {anomalies}

    Provide a comprehensive report including:
    1. Executive Summary
    2. Incident Overview
    3. Investigation Process
    4. Findings and Anomalies
    5. Risk Assessment
    6. Recommendations
    7. Conclusion
    8. Next Steps

    Format the output as a structured JSON object with sections and subsections.
    Include relevant statistics, key metrics, and potential business impact where applicable.