plugin_dir: 'plugins'
active_plugins:
  - custom_anomaly_detection
  - geo_ip_enrichment
  - sentiment_analysis

plugin_settings:
  custom_anomaly_detection:
    threshold: 0.8
  geo_ip_enrichment:
    database_path: '/path/to/geoip/database.mmdb'
  sentiment_analysis:
    model: 'distilbert-base-uncased-finetuned-sst-2-english'