'provider': 'generic'
'use_fine_tuned': false
'url': "http://model.url"
'token': "token"
'models':
  'default':
    'name': "gpt-3.5-turbo-0613"
    'max_tokens': 2000
    'temperature': 0.7
'context': [YOUR CONTEXT IF NOT USING RAG]