version: 1
formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: default
    filename: logs/fraud_investigation.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
loggers:
  '':  # root logger
    level: DEBUG
    handlers: [console, file]
    propagate: no
  src:
    level: DEBUG
    handlers: [console, file]
    propagate: no
  utils:
    level: DEBUG
    handlers: [console, file]
    propagate: no